// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vincible.Data;

#nullable disable

namespace Vincible.Migrations
{
    [DbContext(typeof(VincibleContext))]
    [Migration("20250303220818_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CharacterSuperpower", b =>
                {
                    b.Property<int>("CharactersId")
                        .HasColumnType("int");

                    b.Property<int>("SuperpowersId")
                        .HasColumnType("int");

                    b.HasKey("CharactersId", "SuperpowersId");

                    b.HasIndex("SuperpowersId");

                    b.ToTable("CharacterSuperpower");

                    b.HasData(
                        new
                        {
                            CharactersId = 1,
                            SuperpowersId = 1
                        },
                        new
                        {
                            CharactersId = 1,
                            SuperpowersId = 2
                        },
                        new
                        {
                            CharactersId = 1,
                            SuperpowersId = 3
                        },
                        new
                        {
                            CharactersId = 1,
                            SuperpowersId = 4
                        },
                        new
                        {
                            CharactersId = 1,
                            SuperpowersId = 5
                        },
                        new
                        {
                            CharactersId = 2,
                            SuperpowersId = 6
                        },
                        new
                        {
                            CharactersId = 3,
                            SuperpowersId = 1
                        },
                        new
                        {
                            CharactersId = 3,
                            SuperpowersId = 2
                        },
                        new
                        {
                            CharactersId = 3,
                            SuperpowersId = 3
                        },
                        new
                        {
                            CharactersId = 3,
                            SuperpowersId = 4
                        },
                        new
                        {
                            CharactersId = 3,
                            SuperpowersId = 5
                        },
                        new
                        {
                            CharactersId = 4,
                            SuperpowersId = 1
                        },
                        new
                        {
                            CharactersId = 4,
                            SuperpowersId = 2
                        },
                        new
                        {
                            CharactersId = 4,
                            SuperpowersId = 3
                        },
                        new
                        {
                            CharactersId = 4,
                            SuperpowersId = 4
                        },
                        new
                        {
                            CharactersId = 4,
                            SuperpowersId = 5
                        },
                        new
                        {
                            CharactersId = 5,
                            SuperpowersId = 1
                        },
                        new
                        {
                            CharactersId = 5,
                            SuperpowersId = 2
                        },
                        new
                        {
                            CharactersId = 5,
                            SuperpowersId = 3
                        },
                        new
                        {
                            CharactersId = 5,
                            SuperpowersId = 4
                        },
                        new
                        {
                            CharactersId = 5,
                            SuperpowersId = 5
                        },
                        new
                        {
                            CharactersId = 5,
                            SuperpowersId = 7
                        },
                        new
                        {
                            CharactersId = 6,
                            SuperpowersId = 8
                        },
                        new
                        {
                            CharactersId = 7,
                            SuperpowersId = 9
                        },
                        new
                        {
                            CharactersId = 8,
                            SuperpowersId = 10
                        },
                        new
                        {
                            CharactersId = 8,
                            SuperpowersId = 3
                        },
                        new
                        {
                            CharactersId = 8,
                            SuperpowersId = 4
                        },
                        new
                        {
                            CharactersId = 8,
                            SuperpowersId = 5
                        },
                        new
                        {
                            CharactersId = 9,
                            SuperpowersId = 11
                        },
                        new
                        {
                            CharactersId = 10,
                            SuperpowersId = 8
                        },
                        new
                        {
                            CharactersId = 11,
                            SuperpowersId = 2
                        },
                        new
                        {
                            CharactersId = 11,
                            SuperpowersId = 5
                        },
                        new
                        {
                            CharactersId = 11,
                            SuperpowersId = 12
                        },
                        new
                        {
                            CharactersId = 12,
                            SuperpowersId = 4
                        },
                        new
                        {
                            CharactersId = 14,
                            SuperpowersId = 10
                        },
                        new
                        {
                            CharactersId = 15,
                            SuperpowersId = 1
                        },
                        new
                        {
                            CharactersId = 15,
                            SuperpowersId = 2
                        },
                        new
                        {
                            CharactersId = 15,
                            SuperpowersId = 4
                        },
                        new
                        {
                            CharactersId = 15,
                            SuperpowersId = 5
                        });
                });

            modelBuilder.Entity("Vincible.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 19,
                            Img = "invincible",
                            IsAlive = true,
                            Name = "Invincible"
                        },
                        new
                        {
                            Id = 2,
                            Age = 19,
                            Img = "atom_eve",
                            IsAlive = true,
                            Name = "Atom Eve"
                        },
                        new
                        {
                            Id = 3,
                            Age = 2000,
                            Img = "omni_man",
                            IsAlive = true,
                            Name = "Omni-Man"
                        },
                        new
                        {
                            Id = 4,
                            Img = "allen_the_alien",
                            IsAlive = true,
                            Name = "Allen the Alien"
                        },
                        new
                        {
                            Id = 5,
                            Age = 10000,
                            Img = "the_immortal",
                            IsAlive = true,
                            Name = "The Immortal"
                        },
                        new
                        {
                            Id = 6,
                            Img = "dupli_kate",
                            IsAlive = true,
                            Name = "Dupli-Kate"
                        },
                        new
                        {
                            Id = 7,
                            Img = "rex_splode",
                            IsAlive = true,
                            Name = "Rex Splode"
                        },
                        new
                        {
                            Id = 8,
                            Age = 26,
                            Img = "monster_girl",
                            IsAlive = true,
                            Name = "Monster Girl"
                        },
                        new
                        {
                            Id = 9,
                            Img = "shrinking_rae",
                            IsAlive = true,
                            Name = "Shrinking Rae"
                        },
                        new
                        {
                            Id = 10,
                            Img = "multi_paul",
                            IsAlive = true,
                            Name = "Multi-Paul"
                        },
                        new
                        {
                            Id = 11,
                            Img = "powerplex",
                            IsAlive = true,
                            Name = "Powerplex"
                        },
                        new
                        {
                            Id = 12,
                            Img = "red_rush",
                            IsAlive = false,
                            Name = "Red Rush"
                        },
                        new
                        {
                            Id = 13,
                            Age = 12,
                            Img = "robot",
                            IsAlive = true,
                            Name = "Robot"
                        },
                        new
                        {
                            Id = 14,
                            Img = "shapesmith",
                            IsAlive = true,
                            Name = "Shapesmith"
                        },
                        new
                        {
                            Id = 15,
                            Img = "war_woman",
                            IsAlive = false,
                            Name = "War Woman"
                        });
                });

            modelBuilder.Entity("Vincible.Models.Superpower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Superpowers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "L'utilisateur peut voler ou léviter.",
                            Name = "Vol"
                        },
                        new
                        {
                            Id = 2,
                            Description = "L'utilisateur est significativement résistant contre la majorité des menaces physiques.",
                            Name = "Invulnérabilité"
                        },
                        new
                        {
                            Id = 3,
                            Description = "L'utilisateur guérit significativement rapidement de ses blessures.",
                            Name = "Régénération"
                        },
                        new
                        {
                            Id = 4,
                            Description = "L'utilisateur peut se déplacer significativement rapidement.",
                            Name = "Vitesse surhumaine"
                        },
                        new
                        {
                            Id = 5,
                            Description = "L'utilisateur possède une force physique significativement grande.",
                            Name = "Force surhumaine"
                        },
                        new
                        {
                            Id = 6,
                            Description = "L'utilisateur peut manipuler la matière à un niveau moléculaire et atomique.",
                            Name = "Manipulation de la matière"
                        },
                        new
                        {
                            Id = 7,
                            Description = "L'utilisateur, même si cliniquement mort, peut se regénérer et reprendre vie.",
                            Name = "Résurrection"
                        },
                        new
                        {
                            Id = 8,
                            Description = "L'utilisateur peut dupliquer son corps tout en gardant le contrôle de chacun.",
                            Name = "Réplication"
                        },
                        new
                        {
                            Id = 9,
                            Description = "L'utilisateur peut créer de l'énergie cinétique et la transférer sur des objets pour les faire exploser.",
                            Name = "Charge cinétique"
                        },
                        new
                        {
                            Id = 10,
                            Description = "L'utilisateur peut se transformer ou se métamorphoser.",
                            Name = "Transformation"
                        },
                        new
                        {
                            Id = 11,
                            Description = "L'utilisateur peut réduire et augmenter sa taille sans dépasser sa taille naturelle.",
                            Name = "Réduction de taille"
                        },
                        new
                        {
                            Id = 12,
                            Description = "L'utilisateur peut absorber l'énergie cinétique des objets.",
                            Name = "Absorbtion d'énergie"
                        });
                });

            modelBuilder.Entity("CharacterSuperpower", b =>
                {
                    b.HasOne("Vincible.Models.Character", null)
                        .WithMany()
                        .HasForeignKey("CharactersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vincible.Models.Superpower", null)
                        .WithMany()
                        .HasForeignKey("SuperpowersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
