import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <img src="/images/logo.png" alt="Logo" />
          <Link className="title" href="/">Dix cordes</Link>
          <div className="spacer"></div>
          <Link href="/">Chat</Link>
          <Link href="/account">Connexion</Link>
        </header>
        <main>
          {children}
        </main>
        <footer>
          &copy; Examen formatif - 4204W6
        </footer>
      </body>
    </html>
  );
}
