import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Link from "next/link";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Readonly<{ children: React.ReactNode, params: Promise<{ locale: string }> }>) {

  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html lang={locale}>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="container">

          <Link className="row" href="/">
            <img src="/images/titleIcon.png" alt="Vincinble icon" />
            <h2>Formatif </h2>
            <img src="/images/title.png" alt="Vincible title" />
          </Link>

        </header>

        <nav className="container">
          <div className="row">
            <Link href="/">Personnages</Link>
            <Link href="/superpowers">Super-pouvoirs</Link>
            <Link href="/favorites">Favoris</Link>
          </div>
        </nav>

        <main className="container">
          <NextIntlClientProvider>
            {children}
          </NextIntlClientProvider>
        </main>
      </body>
    </html>
  );
}
