import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="container fond">
          <div className="row">
            <div className="logo">
              <img src="/images/seven.png" alt="Sept" />
            </div>
            <div className="titre">
              🎰 Pas le laboratoire 7
            </div>
          </div>
        </header>

        <nav className="container">
          <div className="row">
            <Link href="/" className="fond">Machine à sous</Link>
            <Link href="/roulette" className="fond">Roulette bilingue</Link>
            <Link href="/spotify" className="fond">Spotify</Link>
          </div>
        </nav>

        <main className="container fond">
          {children}
        </main>

        <footer className="container fond">
          &copy; Définitivement pas le laboratoire 7
        </footer>
      </body>
    </html>
  );
}
