import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Auth from "./auth/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="flex items-center gap-2 text-2xl font-bold">
          <img src="/images/logo.png" alt="Logo" />MyWeebList
        </header>
        <nav>
          <Link href="/"><div>Animes</div></Link>
          <Link href="/auth"><div>Compte</div></Link>
        </nav>
        <main>
          {children}
        </main>
        <footer>
          &copy; T'es-tu bien hydraté(e) aujourd'hui ?
        </footer>
      </body>
    </html>
  );
}
