import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <img src="/images/logo.png" alt="Logo de Stime" />Stime
        </header>
        <nav>
          <Link href="/"><div>Critiques</div></Link>
          <Link href="/auth"><div>Compte</div></Link>
        </nav>
        <main>
          {children}
        </main>
        <footer>
          &copy; As-tu déjeuné aujourd'hui ? 😠
        </footer>
      </body>
    </html>
  );
}
