import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <div className="row">
            <div>
              🎬 Laboratoire 8 ✈️
            </div>
          </div>
        </header>
        <nav>
          <div className="row">
            <Link href="/">Youtube</Link>
            <Link href="/swift">Swift</Link>
            <Link href="/shad">Shad</Link>
          </div>
        </nav>
        <main>
          {children}
        </main>
        <footer>
          <div>
            &copy; Tous droits réservés à Gougueule et Game Frique
          </div>
        </footer>
      </body>
    </html>
  );
}
