// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using labo6_serveur.Data;

#nullable disable

namespace labo6_serveur.Migrations
{
    [DbContext(typeof(labo6_serveurContext))]
    partial class labo6_serveurContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("labo6_serveur.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Correct")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answers = "[\"Oui\",\"Non\"]",
                            Correct = 1,
                            Text = "2100 sera-t-elle une année bissextile ?"
                        },
                        new
                        {
                            Id = 2,
                            Answers = "[\"Oui\",\"Non\"]",
                            Correct = 0,
                            Text = "2400 sera-t-elle une année bissextile ?"
                        },
                        new
                        {
                            Id = 3,
                            Answers = "[\"Taureau\",\"Balance\",\"G\\u00E9meaux\",\"Poissons\"]",
                            Correct = 0,
                            Text = "Quel signe astrologique correspond au 30 avril ?"
                        },
                        new
                        {
                            Id = 4,
                            Answers = "[\"Capricorne\",\"Verseau\",\"Balance\",\"Poissons\"]",
                            Correct = 1,
                            Text = "Quel signe astrologique correspond au 22 janvier ?"
                        },
                        new
                        {
                            Id = 5,
                            Answers = "[\"Marron\",\"Bleu\",\"Jaune\",\"Orange\"]",
                            Correct = 2,
                            Text = "Si on mélange de la lumière rouge et verte, quelle couleur obtient-on ?"
                        },
                        new
                        {
                            Id = 6,
                            Answers = "[\"Marron\",\"Orange\",\"Jaune\",\"Gris\"]",
                            Correct = 0,
                            Text = "Si on mélange de la peinture rouge et verte, quelle couleur obtient-on ?"
                        },
                        new
                        {
                            Id = 7,
                            Answers = "[\"2001\",\"1940\",\"1960\",\"1920\"]",
                            Correct = 1,
                            Text = "En quelle année les femmes ont-elles eu le droit de vote au Québec ?"
                        },
                        new
                        {
                            Id = 8,
                            Answers = "[\"Jamais\",\"2022\",\"2007\",\"2018\"]",
                            Correct = 3,
                            Text = "En quelle année les femmes ont-elles obtenu le droit de conduire en Arabie Saoudite ?"
                        },
                        new
                        {
                            Id = 9,
                            Answers = "[\"Mercure\",\"V\\u00E9nus\",\"Mars\",\"Jupiter\"]",
                            Correct = 1,
                            Text = "Quelle est la planète la plus chaude du système solaire ?"
                        },
                        new
                        {
                            Id = 10,
                            Answers = "[\"Mercure\",\"V\\u00E9nus\",\"Mars\",\"Pluton\"]",
                            Correct = 0,
                            Text = "Quelle est la planète du système solaire qui est la plus proche de la Terre, en moyenne ?"
                        },
                        new
                        {
                            Id = 11,
                            Answers = "[\"Atlantique\",\"Indien\",\"Pacifique\",\"Arctique\"]",
                            Correct = 2,
                            Text = "Quel est le plus grand océan du monde ?"
                        },
                        new
                        {
                            Id = 12,
                            Answers = "[\"Am\\u00E9rique\",\"Afrique\",\"Asie\",\"Europe\"]",
                            Correct = 2,
                            Text = "Quel est le continent avec la plus grande population d'humains ?"
                        },
                        new
                        {
                            Id = 13,
                            Answers = "[\"Or\",\"Osmium\",\"Oxyg\\u00E8ne\",\"Ozone\"]",
                            Correct = 2,
                            Text = "Quel est l’élément chimique dont le symbole est O ?"
                        },
                        new
                        {
                            Id = 14,
                            Answers = "[\"Sydney\",\"Melbourne\",\"Canberra\",\"Perth\"]",
                            Correct = 2,
                            Text = "Quelle est la capitale de l’Australie ?"
                        },
                        new
                        {
                            Id = 15,
                            Answers = "[\"10\",\"11\",\"12\",\"13\"]",
                            Correct = 2,
                            Text = "Combien de côtés a un dodécagone ?"
                        },
                        new
                        {
                            Id = 16,
                            Answers = "[\"\\u00C9gypte\",\"Gr\\u00E8ce\",\"Chine\",\"Inde\"]",
                            Correct = 2,
                            Text = "Quel pays a inventé le papier ?"
                        },
                        new
                        {
                            Id = 17,
                            Answers = "[\"Anglais\",\"Espagnol\",\"Hindi\",\"Mandarin\"]",
                            Correct = 3,
                            Text = "Quelle est la langue maternelle la plus parlée au monde ?"
                        },
                        new
                        {
                            Id = 18,
                            Answers = "[\"Le c\\u0153ur\",\"Le foie\",\"Le cerveau\",\"Les reins\"]",
                            Correct = 2,
                            Text = "Quel organe humain consomme le plus d’énergie au repos ?"
                        },
                        new
                        {
                            Id = 19,
                            Answers = "[\"Nil\",\"Amazone\",\"Yangts\\u00E9\",\"Mississippi\"]",
                            Correct = 1,
                            Text = "Quel est le plus long fleuve du monde ?"
                        },
                        new
                        {
                            Id = 20,
                            Answers = "[\"90\\u00B0C\",\"95\\u00B0C\",\"100\\u00B0C\",\"105\\u00B0C\"]",
                            Correct = 2,
                            Text = "À quelle température l’eau bout-elle au niveau de la mer ?"
                        },
                        new
                        {
                            Id = 21,
                            Answers = "[\"Gu\\u00E9pard\",\"Lion\",\"Antilope\",\"Autruche\"]",
                            Correct = 0,
                            Text = "Quel animal est le plus rapide sur terre ?"
                        },
                        new
                        {
                            Id = 22,
                            Answers = "[\"Aluminium\",\"Lithium\",\"Magn\\u00E9sium\",\"Titane\"]",
                            Correct = 1,
                            Text = "Quel est le métal le plus léger ?"
                        },
                        new
                        {
                            Id = 23,
                            Answers = "[\"So\",\"Sd\",\"Na\",\"Sn\"]",
                            Correct = 2,
                            Text = "Quel est le symbole chimique du sodium ?"
                        },
                        new
                        {
                            Id = 24,
                            Answers = "[\"9\",\"10\",\"11\",\"12\"]",
                            Correct = 2,
                            Text = "Combien de joueurs y a-t-il sur le terrain par équipe au football ?"
                        },
                        new
                        {
                            Id = 25,
                            Answers = "[\"Monaco\",\"Saint-Marin\",\"Vatican\",\"Liechtenstein\"]",
                            Correct = 2,
                            Text = "Quel est le plus petit pays du monde ?"
                        },
                        new
                        {
                            Id = 26,
                            Answers = "[\"Jupiter\",\"Saturne\",\"Uranus\",\"Neptune\"]",
                            Correct = 1,
                            Text = "Quelle planète possède les anneaux les plus visibles ?"
                        },
                        new
                        {
                            Id = 27,
                            Answers = "[\"Gobi\",\"Sahara\",\"Kalahari\",\"Atacama\"]",
                            Correct = 1,
                            Text = "Quel est le nom du plus grand désert chaud du monde ?"
                        },
                        new
                        {
                            Id = 28,
                            Answers = "[\"Thomas Edison\",\"Nikola Tesla\",\"Alexander Graham Bell\",\"Marconi\"]",
                            Correct = 2,
                            Text = "Quel est l’inventeur du téléphone ?"
                        },
                        new
                        {
                            Id = 29,
                            Answers = "[\"28\",\"30\",\"32\",\"34\"]",
                            Correct = 2,
                            Text = "Quel est le nombre de dents chez un adulte en bonne santé ?"
                        },
                        new
                        {
                            Id = 30,
                            Answers = "[\"Oxyg\\u00E8ne\",\"Azote\",\"Dioxyde de carbone\",\"Argon\"]",
                            Correct = 1,
                            Text = "Quel est le gaz le plus présent dans l’atmosphère terrestre ?"
                        },
                        new
                        {
                            Id = 31,
                            Answers = "[\"Chine\",\"Inde\",\"\\u00C9tats-Unis\",\"Indon\\u00E9sie\"]",
                            Correct = 1,
                            Text = "Quel est le pays le plus peuplé du monde en 2024 ?"
                        },
                        new
                        {
                            Id = 32,
                            Answers = "[\"300 000 km/s\",\"150 000 km/s\",\"30 000 km/s\",\"3 000 km/s\"]",
                            Correct = 0,
                            Text = "Quelle est la vitesse approximative de la lumière ?"
                        },
                        new
                        {
                            Id = 33,
                            Answers = "[\"\\u00C9l\\u00E9phant d\\u2019Afrique\",\"Rhinoc\\u00E9ros\",\"Girafe\",\"Hippopotame\"]",
                            Correct = 0,
                            Text = "Quel est le plus grand mammifère terrestre ?"
                        },
                        new
                        {
                            Id = 34,
                            Answers = "[\"4\",\"5\",\"6\",\"7\"]",
                            Correct = 0,
                            Text = "Combien de cordes possède un violon ?"
                        },
                        new
                        {
                            Id = 35,
                            Answers = "[\"Lune\",\"Phobos\",\"Titan\",\"Io\"]",
                            Correct = 0,
                            Text = "Quel est le nom du satellite naturel de la Terre ?"
                        },
                        new
                        {
                            Id = 36,
                            Answers = "[\"K2\",\"Mont Everest\",\"Kangchenjunga\",\"Mont Blanc\"]",
                            Correct = 1,
                            Text = "Quel est le plus haut sommet du monde ?"
                        },
                        new
                        {
                            Id = 37,
                            Answers = "[\"Won\",\"Yen\",\"Yuan\",\"Ringgit\"]",
                            Correct = 1,
                            Text = "Quelle est la monnaie officielle du Japon ?"
                        },
                        new
                        {
                            Id = 38,
                            Answers = "[\"Newton\",\"Galil\\u00E9e\",\"Einstein\",\"Bohr\"]",
                            Correct = 2,
                            Text = "Quel scientifique a proposé la théorie de la relativité ?"
                        },
                        new
                        {
                            Id = 39,
                            Answers = "[\"Le foie\",\"La peau\",\"Les poumons\",\"Le cerveau\"]",
                            Correct = 1,
                            Text = "Quel est le plus grand organe du corps humain ?"
                        },
                        new
                        {
                            Id = 40,
                            Answers = "[\"720\",\"1440\",\"2880\",\"4320\"]",
                            Correct = 1,
                            Text = "Combien de minutes y a-t-il dans une journée ?"
                        },
                        new
                        {
                            Id = 41,
                            Answers = "[\"Chine\",\"Cor\\u00E9e du Sud\",\"Japon\",\"Tha\\u00EFlande\"]",
                            Correct = 2,
                            Text = "Quel pays est surnommé le \"Pays du Soleil-Levant\" ?"
                        },
                        new
                        {
                            Id = 42,
                            Answers = "[\"HO\",\"H2O\",\"H2O2\",\"OH2\"]",
                            Correct = 1,
                            Text = "Quelle est la formule chimique de l’eau ?"
                        },
                        new
                        {
                            Id = 43,
                            Answers = "[\"5\",\"6\",\"7\",\"8\"]",
                            Correct = 1,
                            Text = "Combien de côtés possède un hexagone ?"
                        },
                        new
                        {
                            Id = 44,
                            Answers = "[\"Barom\\u00E8tre\",\"Thermom\\u00E8tre\",\"Hygrom\\u00E8tre\",\"An\\u00E9mom\\u00E8tre\"]",
                            Correct = 1,
                            Text = "Quel est l’instrument principal pour mesurer la température ?"
                        },
                        new
                        {
                            Id = 45,
                            Answers = "[\"Canada\",\"Chine\",\"\\u00C9tats-Unis\",\"Russie\"]",
                            Correct = 3,
                            Text = "Quel est le plus grand pays du monde par superficie ?"
                        },
                        new
                        {
                            Id = 46,
                            Answers = "[\"Le vent\",\"La rotation de la Terre\",\"La gravit\\u00E9 de la Lune\",\"La gravit\\u00E9 du Soleil\"]",
                            Correct = 2,
                            Text = "Quel est le nom du phénomène qui provoque les marées ?"
                        },
                        new
                        {
                            Id = 47,
                            Answers = "[\"Vert\",\"Jaune\",\"Orange\",\"Rouge\"]",
                            Correct = 2,
                            Text = "Quelle est la couleur complémentaire du bleu ?"
                        },
                        new
                        {
                            Id = 48,
                            Answers = "[\"\\u00C9checs\",\"Go\",\"Mancala\",\"Backgammon\"]",
                            Correct = 2,
                            Text = "Quel est le plus ancien jeu de société connu ?"
                        },
                        new
                        {
                            Id = 49,
                            Answers = "[\"\\u00C9trier\",\"Marteau\",\"Enclume\",\"Rotule\"]",
                            Correct = 0,
                            Text = "Quel est le nom du plus petit os du corps humain ?"
                        },
                        new
                        {
                            Id = 50,
                            Answers = "[\"Mercure\",\"V\\u00E9nus\",\"Mars\",\"Jupiter\"]",
                            Correct = 2,
                            Text = "Quelle planète est surnommée la planète rouge ?"
                        },
                        new
                        {
                            Id = 51,
                            Answers = "[\"Dinosaure\",\"\\u00C9l\\u00E9phant d\\u2019Afrique\",\"Baleine bleue\",\"M\\u00E9galodon\"]",
                            Correct = 2,
                            Text = "Quel est le plus grand animal ayant jamais existé ?"
                        },
                        new
                        {
                            Id = 52,
                            Answers = "[\"Fe\",\"Ir\",\"Fr\",\"Fi\"]",
                            Correct = 0,
                            Text = "Quel est le symbole chimique du fer ?"
                        },
                        new
                        {
                            Id = 53,
                            Answers = "[\"365\",\"366\",\"367\",\"364\"]",
                            Correct = 1,
                            Text = "Combien de jours compte une année bissextile ?"
                        },
                        new
                        {
                            Id = 54,
                            Answers = "[\"\\u00C9gypte\",\"\\u00C9thiopie\",\"Nigeria\",\"Afrique du Sud\"]",
                            Correct = 2,
                            Text = "Quel pays possède la plus grande population en Afrique ?"
                        },
                        new
                        {
                            Id = 55,
                            Answers = "[\"Rio de Janeiro\",\"S\\u00E3o Paulo\",\"Bras\\u00EDlia\",\"Salvador\"]",
                            Correct = 2,
                            Text = "Quelle est la capitale du Brésil ?"
                        },
                        new
                        {
                            Id = 56,
                            Answers = "[\"Androm\\u00E8de\",\"Voie lact\\u00E9e\",\"Messier 87\",\"Sombrero\"]",
                            Correct = 1,
                            Text = "Quel est le nom de la galaxie dans laquelle se trouve la Terre ?"
                        },
                        new
                        {
                            Id = 57,
                            Answers = "[\"6\",\"7\",\"8\",\"9\"]",
                            Correct = 2,
                            Text = "Combien de côtés possède un octogone ?"
                        },
                        new
                        {
                            Id = 58,
                            Answers = "[\"Oxyg\\u00E8ne\",\"Azote\",\"Dioxyde de carbone\",\"Vapeur d\\u2019eau\"]",
                            Correct = 3,
                            Text = "Quel est le principal gaz responsable de l’effet de serre naturel ?"
                        },
                        new
                        {
                            Id = 59,
                            Answers = "[\"Italie\",\"Gr\\u00E8ce\",\"France\",\"\\u00C9gypte\"]",
                            Correct = 1,
                            Text = "Quel est le pays d’origine des Jeux olympiques ?"
                        },
                        new
                        {
                            Id = 60,
                            Answers = "[\"Horaire\",\"Antihoraire\",\"Variable\",\"Elle ne tourne pas\"]",
                            Correct = 1,
                            Text = "Quel est le sens de rotation de la Terre vue depuis le pôle Nord ?"
                        },
                        new
                        {
                            Id = 61,
                            Answers = "[\"Volt\",\"Watt\",\"Amp\\u00E8re\",\"Ohm\"]",
                            Correct = 2,
                            Text = "Quelle unité mesure l’intensité du courant électrique ?"
                        },
                        new
                        {
                            Id = 62,
                            Answers = "[\"Lac Victoria\",\"Lac Ba\\u00EFkal\",\"Lac Sup\\u00E9rieur\",\"Lac Tanganyika\"]",
                            Correct = 2,
                            Text = "Quel est le plus grand lac d’eau douce du monde en superficie ?"
                        },
                        new
                        {
                            Id = 63,
                            Answers = "[\"7\",\"8\",\"9\",\"10\"]",
                            Correct = 1,
                            Text = "Combien de planètes composent le système solaire ?"
                        },
                        new
                        {
                            Id = 64,
                            Answers = "[\"Canada\",\"Russie\",\"Norv\\u00E8ge\",\"Danemark\"]",
                            Correct = 1,
                            Text = "Quel est le pays le plus au nord du monde ?"
                        },
                        new
                        {
                            Id = 65,
                            Answers = "[\"Poumons\",\"Foie\",\"Reins\",\"Pancr\\u00E9as\"]",
                            Correct = 2,
                            Text = "Quel organe permet principalement de filtrer le sang ?"
                        },
                        new
                        {
                            Id = 66,
                            Answers = "[\"4\",\"5\",\"6\",\"7\"]",
                            Correct = 1,
                            Text = "Quel est le nombre minimum de joueurs pour former une équipe de basketball sur le terrain ?"
                        },
                        new
                        {
                            Id = 67,
                            Answers = "[\"Toronto\",\"Montr\\u00E9al\",\"Ottawa\",\"Vancouver\"]",
                            Correct = 2,
                            Text = "Quelle est la capitale du Canada ?"
                        },
                        new
                        {
                            Id = 68,
                            Answers = "[\"Plomb\",\"Mercure\",\"\\u00C9tain\",\"Zinc\"]",
                            Correct = 1,
                            Text = "Quel métal est liquide à température ambiante ?"
                        },
                        new
                        {
                            Id = 69,
                            Answers = "[\"Mars\",\"V\\u00E9nus\",\"Jupiter\",\"Mercure\"]",
                            Correct = 1,
                            Text = "Quelle planète a la durée de jour la plus longue ?"
                        },
                        new
                        {
                            Id = 70,
                            Answers = "[\"3.12\",\"3.14\",\"3.16\",\"3.18\"]",
                            Correct = 1,
                            Text = "Quelle est la valeur de π (pi) arrondie à deux décimales ?"
                        },
                        new
                        {
                            Id = 71,
                            Answers = "[\"Etna\",\"Mauna Kea\",\"Olympus Mons\",\"V\\u00E9suve\"]",
                            Correct = 2,
                            Text = "Quel est le nom du plus grand volcan du système solaire ?"
                        },
                        new
                        {
                            Id = 72,
                            Answers = "[\"Fission\",\"Combustion\",\"Fusion nucl\\u00E9aire\",\"Radioactivit\\u00E9\"]",
                            Correct = 2,
                            Text = "Quelle est la principale source d’énergie du Soleil ?"
                        },
                        new
                        {
                            Id = 73,
                            Answers = "[\"France\",\"Espagne\",\"Italie\",\"Gr\\u00E8ce\"]",
                            Correct = 2,
                            Text = "Quel est le pays d’origine de la pizza ?"
                        },
                        new
                        {
                            Id = 74,
                            Answers = "[\"0\",\"1\",\"2\",\"3\"]",
                            Correct = 2,
                            Text = "Quel est le plus petit nombre premier ?"
                        },
                        new
                        {
                            Id = 75,
                            Answers = "[\"Mer Rouge\",\"Mer Morte\",\"Mer Noire\",\"Mer M\\u00E9diterran\\u00E9e\"]",
                            Correct = 1,
                            Text = "Quelle mer est la plus salée ?"
                        },
                        new
                        {
                            Id = 76,
                            Answers = "[\"Tibia\",\"F\\u00E9mur\",\"Hum\\u00E9rus\",\"Radius\"]",
                            Correct = 1,
                            Text = "Quel est l’os le plus long du corps humain ?"
                        },
                        new
                        {
                            Id = 77,
                            Answers = "[\"Oslo\",\"Helsinki\",\"Reykjav\\u00EDk\",\"Stockholm\"]",
                            Correct = 2,
                            Text = "Quelle est la capitale de l’Islande ?"
                        },
                        new
                        {
                            Id = 78,
                            Answers = "[\"4\",\"5\",\"6\",\"8\"]",
                            Correct = 2,
                            Text = "Combien de faces possède un cube ?"
                        },
                        new
                        {
                            Id = 79,
                            Answers = "[\"Calcium\",\"Silicium\",\"Sable\",\"Carbone\"]",
                            Correct = 2,
                            Text = "Quel est le principal constituant du verre ?"
                        },
                        new
                        {
                            Id = 80,
                            Answers = "[\"\\u00C9tats-Unis\",\"Espagne\",\"Italie\",\"France\"]",
                            Correct = 3,
                            Text = "Quel est le pays le plus visité au monde ?"
                        },
                        new
                        {
                            Id = 81,
                            Answers = "[\"Manteau\",\"Noyau\",\"Cro\\u00FBte\",\"Lithosph\\u00E8re\"]",
                            Correct = 2,
                            Text = "Quel est le nom de la couche externe de la Terre ?"
                        },
                        new
                        {
                            Id = 82,
                            Answers = "[\"22\",\"24\",\"26\",\"28\"]",
                            Correct = 1,
                            Text = "Quel est le nombre de lettres dans l’alphabet grec ?"
                        },
                        new
                        {
                            Id = 83,
                            Answers = "[\"Jupiter\",\"Saturne\",\"Uranus\",\"Neptune\"]",
                            Correct = 1,
                            Text = "Quelle planète possède le plus de lunes connues ?"
                        },
                        new
                        {
                            Id = 84,
                            Answers = "[\"Carot\\u00E8ne\",\"Chlorophylle\",\"M\\u00E9lanine\",\"Xanthophylle\"]",
                            Correct = 1,
                            Text = "Quel est le principal pigment vert des plantes ?"
                        },
                        new
                        {
                            Id = 85,
                            Answers = "[\"Gambie\",\"Seychelles\",\"Comores\",\"Lesotho\"]",
                            Correct = 1,
                            Text = "Quel est le plus petit pays d’Afrique ?"
                        },
                        new
                        {
                            Id = 86,
                            Answers = "[\"Auckland\",\"Christchurch\",\"Wellington\",\"Hamilton\"]",
                            Correct = 2,
                            Text = "Quelle est la capitale de la Nouvelle-Zélande ?"
                        },
                        new
                        {
                            Id = 87,
                            Answers = "[\"Ag\",\"Au\",\"Or\",\"Go\"]",
                            Correct = 1,
                            Text = "Quel est le symbole chimique de l’or ?"
                        },
                        new
                        {
                            Id = 88,
                            Answers = "[\"12 heures\",\"24 heures\",\"36 heures\",\"48 heures\"]",
                            Correct = 1,
                            Text = "Quelle est la durée approximative de rotation de la Terre sur elle-même ?"
                        },
                        new
                        {
                            Id = 89,
                            Answers = "[\"R\\u00E9cif de Belize\",\"Grande barri\\u00E8re de corail\",\"R\\u00E9cif des Maldives\",\"R\\u00E9cif des Cara\\u00EFbes\"]",
                            Correct = 1,
                            Text = "Quel est le nom du plus grand récif corallien du monde ?"
                        },
                        new
                        {
                            Id = 90,
                            Answers = "[\"Europe\",\"Antarctique\",\"Oc\\u00E9anie\",\"Am\\u00E9rique du Sud\"]",
                            Correct = 2,
                            Text = "Quel est le plus petit continent ?"
                        },
                        new
                        {
                            Id = 91,
                            Answers = "[\"Victor Hugo\",\"Antoine de Saint-Exup\\u00E9ry\",\"Jules Verne\",\"Albert Camus\"]",
                            Correct = 1,
                            Text = "Quel est l’auteur de \"Le Petit Prince\" ?"
                        },
                        new
                        {
                            Id = 92,
                            Answers = "[\"Espagnol\",\"Portugais\",\"Fran\\u00E7ais\",\"Anglais\"]",
                            Correct = 1,
                            Text = "Quelle est la langue officielle du Brésil ?"
                        },
                        new
                        {
                            Id = 93,
                            Answers = "[\"Gobi\",\"Antarctique\",\"Arctique\",\"Sib\\u00E9rien\"]",
                            Correct = 1,
                            Text = "Quel est le plus grand désert froid du monde ?"
                        },
                        new
                        {
                            Id = 94,
                            Answers = "[\"Mercure\",\"Mars\",\"V\\u00E9nus\",\"Pluton\"]",
                            Correct = 0,
                            Text = "Quelle est la plus petite planète du système solaire ?"
                        },
                        new
                        {
                            Id = 95,
                            Answers = "[\"200\",\"250\",\"300\",\"350\"]",
                            Correct = 2,
                            Text = "Quel est le nombre maximum de points dans un strike au bowling ?"
                        },
                        new
                        {
                            Id = 96,
                            Answers = "[\"Fujita\",\"Mercalli\",\"Richter\",\"Beaufort\"]",
                            Correct = 2,
                            Text = "Quel est le nom de l’échelle qui mesure les tremblements de terre ?"
                        },
                        new
                        {
                            Id = 97,
                            Answers = "[\"Vitamine A\",\"Vitamine B12\",\"Vitamine C\",\"Vitamine D\"]",
                            Correct = 3,
                            Text = "Quelle vitamine est principalement produite grâce au soleil ?"
                        },
                        new
                        {
                            Id = 98,
                            Answers = "[\"Argentine\",\"Colombie\",\"P\\u00E9rou\",\"Br\\u00E9sil\"]",
                            Correct = 3,
                            Text = "Quel est le plus grand pays d’Amérique du Sud ?"
                        },
                        new
                        {
                            Id = 99,
                            Answers = "[\"Hum\\u00E9rus\",\"Cubitus\",\"F\\u00E9mur\",\"Omoplate\"]",
                            Correct = 1,
                            Text = "Quel est le principal os de l’avant-bras ?"
                        },
                        new
                        {
                            Id = 100,
                            Answers = "[\"\\u00C9cureuil volant\",\"Chauve-souris\",\"Colibri\",\"Planeur\"]",
                            Correct = 1,
                            Text = "Quel est le seul mammifère capable de voler ?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
