// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [{type: 'autogenerated', dirName: '01-notes'}],
  tp: [{type: 'autogenerated', dirName: '02-tp'}],
  labos: [{type:'autogenerated', dirName:'03-labos'}],
  cours: [{type: 'autogenerated', dirName: '04-cours'}]
};

module.exports = sidebars;
